---
swagger: "2.0"
info:
  description: "API for common-to-rare disease gene-list producer."
  version: "1.3.0"
  title: "API for common-to-rare disease gene-list producer"
host: "sharpener.ncats.io"
basePath: "/common_to_rare_disease"
schemes:
- "https"
paths:
  /transformer_info:
    get:
      tags:
      - "transformer"
      summary: "Retrieve transformer info"
      description: "Provides information about the transformer."
      operationId: "transformer_info_get"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/transformer_info"
      x-swagger-router-controller: "swagger_server.controllers.transformer_controller"
  /transform:
    post:
      tags:
      - "transformer"
      operationId: "transform_post"
      parameters:
      - in: "body"
        name: "query"
        description: "Performs transformer query."
        required: true
        schema:
          $ref: "#/definitions/transformer_query"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/gene_info"
        400:
          description: "bad request"
          schema:
            $ref: "#/definitions/error_msg"
        500:
          description: "internal server error"
          schema:
            $ref: "#/definitions/error_msg"
      x-swagger-router-controller: "swagger_server.controllers.transformer_controller"
definitions:
  transformer_query:
    type: "object"
    required:
    - "controls"
    properties:
      genes:
        type: "array"
        description: "List of genes that will be transformed. Required for expanders\
          \ and filters; should be omitted for producers."
        items:
          $ref: "#/definitions/gene_info"
      controls:
        type: "array"
        description: "Values that control the behavior of the transformer. Names of\
          \ the controls must match the names specified in the transformer's definition\
          \ and values must match types (and possibly  allowed_values) specified in\
          \ the transformer's definition."
        items:
          $ref: "#/definitions/property"
  gene_info:
    type: "object"
    required:
    - "gene_id"
    properties:
      gene_id:
        type: "string"
        description: "Id of the gene."
      identifiers:
        $ref: "#/definitions/gene_info_identifiers"
      attributes:
        type: "array"
        description: "Additional information about the gene and provenance about gene-list\
          \ membership. Sharpener will use myGene.info to add 'gene_symbol', 'synonyms',\
          \ and 'gene_name' to every gene.  Multiple synonyms are separated by semicolons."
        items:
          $ref: "#/definitions/attribute"
      source:
        type: "string"
        description: "Name of a transformer that added gene to the gene list."
    example:
      identifiers:
        mim: "MIM:608958"
        entrez: "NCBIGene:100"
        ensembl:
        - "ENSEMBL:ENSG00000196839"
        - "ENSEMBL:ENSG00000196839"
        hgnc: "HGNC:186"
        mygene_info: "100"
      attributes:
      - name: "name"
        source: "source"
        value: "value"
        url: "url"
      - name: "name"
        source: "source"
        value: "value"
        url: "url"
      source: "source"
      gene_id: "gene_id"
  attribute:
    type: "object"
    required:
    - "name"
    - "source"
    - "value"
    properties:
      name:
        type: "string"
        description: "Name of the attribute."
      value:
        type: "string"
        description: "Value of the attribute."
      source:
        type: "string"
        description: "Transformer that produced the attribute's value."
      url:
        type: "string"
        description: "URL for additional information."
    example:
      name: "name"
      source: "source"
      value: "value"
      url: "url"
  property:
    type: "object"
    required:
    - "name"
    - "value"
    properties:
      name:
        type: "string"
      value:
        type: "string"
  transformer_info:
    type: "object"
    required:
    - "description"
    - "function"
    - "name"
    - "parameters"
    - "required_attributes"
    properties:
      name:
        type: "string"
        description: "Name of the transformer."
      label:
        type: "string"
        description: "Short label for GUI display."
      version:
        type: "string"
        description: "Transformer's version."
      function:
        type: "string"
        description: "Function of the transformer, one of 'producer', 'expander',\
          \ 'filter'."
        enum:
        - "producer"
        - "expander"
        - "filter"
      description:
        type: "string"
        description: "Description of the transformer."
      properties:
        $ref: "#/definitions/transformer_info_properties"
      parameters:
        type: "array"
        description: "Parameters used to control the transformer."
        items:
          $ref: "#/definitions/parameter"
      required_attributes:
        type: "array"
        description: "Gene attributes required by the transformer"
        items:
          type: "string"
    description: "Definition of the transformer."
    example:
      required_attributes:
      - "required_attributes"
      - "required_attributes"
      function: "producer"
      name: "name"
      description: "description"
      label: "label"
      version: "version"
      parameters:
      - allowed_values:
        - "allowed_values"
        - "allowed_values"
        biolink_class: "biolink_class"
        default: "default"
        allowed_range:
        - 0.80082819046101150206595775671303272247314453125
        - 0.80082819046101150206595775671303272247314453125
        name: "name"
        suggested_values: "suggested_values"
        lookup_url: "lookup_url"
        type: "Boolean"
      - allowed_values:
        - "allowed_values"
        - "allowed_values"
        biolink_class: "biolink_class"
        default: "default"
        allowed_range:
        - 0.80082819046101150206595775671303272247314453125
        - 0.80082819046101150206595775671303272247314453125
        name: "name"
        suggested_values: "suggested_values"
        lookup_url: "lookup_url"
        type: "Boolean"
      properties:
        list_predicate: "list_predicate"
        method: "method"
        member_predicate: "member_predicate"
        source_url: "source_url"
  parameter:
    type: "object"
    required:
    - "default"
    - "name"
    - "type"
    properties:
      name:
        type: "string"
        description: "Name of the parameter."
      type:
        type: "string"
        description: "Type of the parameter, one of 'Boolean', 'int', 'double', 'string'."
        enum:
        - "Boolean"
        - "int"
        - "double"
        - "string"
      default:
        type: "string"
        description: "Default value of the parameter."
      biolink_class:
        type: "string"
        description: "Biolink class of the paramater. Applicable to producers only\
          \ and only one parameter can have a biolink class."
      allowed_values:
        type: "array"
        description: "Allowed values for the parameter."
        items:
          type: "string"
      allowed_range:
        type: "array"
        description: "Allowed range for values of the parameter."
        items:
          type: "number"
        maxItems: 2
        minItems: 2
      suggested_values:
        type: "string"
        description: "Suggested value range for the parameter."
      lookup_url:
        type: "string"
        description: "URL to search for suitable parameter values."
    example:
      allowed_values:
      - "allowed_values"
      - "allowed_values"
      biolink_class: "biolink_class"
      default: "default"
      allowed_range:
      - 0.80082819046101150206595775671303272247314453125
      - 0.80082819046101150206595775671303272247314453125
      name: "name"
      suggested_values: "suggested_values"
      lookup_url: "lookup_url"
      type: "Boolean"
  error_msg:
    type: "object"
    properties:
      status:
        type: "integer"
      title:
        type: "string"
      detail:
        type: "string"
      type:
        type: "string"
  gene_info_identifiers:
    properties:
      entrez:
        type: "string"
        example: "NCBIGene:100"
        description: "Entrez gene id (CURIE)."
      hgnc:
        type: "string"
        example: "HGNC:186"
        description: "HGNC gene id (CURIE)."
      mim:
        type: "string"
        example: "MIM:608958"
        description: "OMIM gene id (CURIE)."
      ensembl:
        type: "array"
        description: "ENSEMBL gene id (CURIE)."
        items:
          type: "string"
          example: "ENSEMBL:ENSG00000196839"
      mygene_info:
        type: "string"
        example: "100"
        description: "myGene.info primary id."
    example:
      mim: "MIM:608958"
      entrez: "NCBIGene:100"
      ensembl:
      - "ENSEMBL:ENSG00000196839"
      - "ENSEMBL:ENSG00000196839"
      hgnc: "HGNC:186"
      mygene_info: "100"
  transformer_info_properties:
    properties:
      list_predicate:
        type: "string"
        description: "BioLink-model predicate describing relationship between input\
          \ and output gene lists."
      member_predicate:
        type: "string"
        description: "BioLink-model predicate describing relationship between input\
          \ and output genes."
      source_url:
        type: "string"
        description: "URL for underlying data or a wrapped service."
      method:
        type: "string"
        description: "A method used to generate output gene lists."
    description: "Additional metadata for the transformer."
    example:
      list_predicate: "list_predicate"
      method: "method"
      member_predicate: "member_predicate"
      source_url: "source_url"
